### PR TITLE
added images

### LINKED ISSUE #4: Better logo
Need to have a better logo for the extension. Contributions are welcome. 

/cc @sahilkhose

### PR DESCRIPTION
**Pull request by RohithBoppey**
I have added images inside src/images folder and also included the backgrounded one. Please take a look at it.

### CODE REVIEW

**Review by AdityaKane2001 — CHANGES_REQUESTED** [review]
@RohithBoppey 

In the images without the background, could you keep the white background which is INSIDE the PDF icon? That way when deployed it will be more noticeable.

**Comment by RohithBoppey** [comment]
> @RohithBoppey
> 
> In the images without the background, could you keep the white background which is INSIDE the PDF icon? That way when deployed it will be more noticeable.

Yeah okay, I'll try doing it.

**Comment by AdityaKane2001** [comment]
Yeah I guess there is an edit option on remove.bg website.

**Comment by AdityaKane2001** [comment]
One last thing, please don't keep the images in a separate directory, keep them in the src directory along with the rest of the code.

**Comment by RohithBoppey** [comment]
> One last thing, please don't keep the images in a separate directory, keep them in the src directory along with the rest of the code.

Okay.

**Review by AdityaKane2001 — APPROVED** [review]

**Pull request merged**
